[2025-07-25T21:48:11.957+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-25T21:48:12.342+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sample_ETL.load_order_and_delivery_data manual__2025-07-25T21:07:04.673260+00:00 [queued]>
[2025-07-25T21:48:12.386+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sample_ETL.load_order_and_delivery_data manual__2025-07-25T21:07:04.673260+00:00 [queued]>
[2025-07-25T21:48:12.388+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 1
[2025-07-25T21:48:12.513+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_order_and_delivery_data> on 2025-07-25 21:07:04.673260+00:00
[2025-07-25T21:48:12.546+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=158) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-25T21:48:12.550+0000] {standard_task_runner.py:63} INFO - Started process 165 to run task
[2025-07-25T21:48:12.547+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sample_ETL', 'load_order_and_delivery_data', 'manual__2025-07-25T21:07:04.673260+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/sample_ETL.py', '--cfg-path', '/tmp/tmp1focobf3']
[2025-07-25T21:48:12.561+0000] {standard_task_runner.py:91} INFO - Job 55: Subtask load_order_and_delivery_data
[2025-07-25T21:48:12.922+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-25T21:48:13.522+0000] {task_command.py:426} INFO - Running <TaskInstance: sample_ETL.load_order_and_delivery_data manual__2025-07-25T21:07:04.673260+00:00 [running]> on host 9f2231592208
[2025-07-25T21:48:14.347+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sample_ETL' AIRFLOW_CTX_TASK_ID='load_order_and_delivery_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-25T21:07:04.673260+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-25T21:07:04.673260+00:00'
[2025-07-25T21:48:14.353+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-25T21:48:14.483+0000] {logging_mixin.py:188} INFO - ðŸš€ Starting load_order_and_delivery_data
[2025-07-25T21:48:14.509+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.9', 9092)]>: connecting to kafka:9092 [('172.18.0.9', 9092) IPv4]
[2025-07-25T21:48:14.513+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.9', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-07-25T21:48:14.515+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.9', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-07-25T21:48:14.518+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.04 secs
[2025-07-25T21:48:14.564+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.9', 9092)]>: connecting to kafka:9092 [('172.18.0.9', 9092) IPv4]
[2025-07-25T21:48:14.566+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.9', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-07-25T21:48:14.567+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.9', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-07-25T21:48:14.568+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.10 secs
[2025-07-25T21:48:14.666+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.9', 9092)]>: connecting to kafka:9092 [('172.18.0.9', 9092) IPv4]
[2025-07-25T21:48:14.668+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.9', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-07-25T21:48:14.669+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.9', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-07-25T21:48:14.671+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.20 secs
[2025-07-25T21:48:14.873+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.9', 9092)]>: connecting to kafka:9092 [('172.18.0.9', 9092) IPv4]
[2025-07-25T21:48:14.875+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.9', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-07-25T21:48:14.876+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.9', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-07-25T21:48:14.877+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.37 secs
[2025-07-25T21:48:15.245+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.9', 9092)]>: connecting to kafka:9092 [('172.18.0.9', 9092) IPv4]
[2025-07-25T21:48:15.248+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.9', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-07-25T21:48:15.249+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.9', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-07-25T21:48:15.251+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.81 secs
[2025-07-25T21:48:16.066+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.9', 9092)]>: connecting to kafka:9092 [('172.18.0.9', 9092) IPv4]
[2025-07-25T21:48:16.068+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.9', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-07-25T21:48:16.069+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.9', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-07-25T21:48:16.070+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.43 secs
[2025-07-25T21:48:16.507+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-25T21:48:16.508+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/script2.py", line 91, in load_order_and_delivery_data
    producer = KafkaProducer(
               ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py", line 481, in __init__
    client = self.config['kafka_client'](
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py", line 262, in __init__
    self.config['api_version'] = self.check_version()
                                 ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py", line 1074, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-07-25T21:48:16.638+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=sample_ETL, task_id=load_order_and_delivery_data, run_id=manual__2025-07-25T21:07:04.673260+00:00, execution_date=20250725T210704, start_date=20250725T214812, end_date=20250725T214816
[2025-07-25T21:48:16.687+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 55 for task load_order_and_delivery_data (NoBrokersAvailable; 165)
[2025-07-25T21:48:16.719+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-25T21:48:16.851+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-25T21:48:16.855+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
