[2025-07-26T08:26:53.812+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-26T08:26:53.877+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sample_ETL.load_order_and_delivery_data manual__2025-07-26T08:21:57.926164+00:00 [queued]>
[2025-07-26T08:26:53.888+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sample_ETL.load_order_and_delivery_data manual__2025-07-26T08:21:57.926164+00:00 [queued]>
[2025-07-26T08:26:53.889+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-26T08:26:53.926+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_order_and_delivery_data> on 2025-07-26 08:21:57.926164+00:00
[2025-07-26T08:26:53.936+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=50) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-26T08:26:53.939+0000] {standard_task_runner.py:63} INFO - Started process 51 to run task
[2025-07-26T08:26:53.936+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sample_ETL', 'load_order_and_delivery_data', 'manual__2025-07-26T08:21:57.926164+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/sample_ETL.py', '--cfg-path', '/tmp/tmp8xsrj4m_']
[2025-07-26T08:26:53.940+0000] {standard_task_runner.py:91} INFO - Job 70: Subtask load_order_and_delivery_data
[2025-07-26T08:26:54.017+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-26T08:26:54.127+0000] {task_command.py:426} INFO - Running <TaskInstance: sample_ETL.load_order_and_delivery_data manual__2025-07-26T08:21:57.926164+00:00 [running]> on host 31da7eada680
[2025-07-26T08:26:54.397+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sample_ETL' AIRFLOW_CTX_TASK_ID='load_order_and_delivery_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-26T08:21:57.926164+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-26T08:21:57.926164+00:00'
[2025-07-26T08:26:54.399+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-26T08:26:54.414+0000] {logging_mixin.py:188} INFO - üöÄ Starting ETL with JSON files
[2025-07-26T08:26:54.418+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.7', 9092)]>: connecting to kafka:9092 [('172.18.0.7', 9092) IPv4]
[2025-07-26T08:26:54.873+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.7', 9092)]>: Broker version identified as 2.6
[2025-07-26T08:26:54.874+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Connection complete.
[2025-07-26T08:26:55.068+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.7', 9092)]>: connecting to kafka:9092 [('172.18.0.7', 9092) IPv4]
[2025-07-26T08:26:55.069+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Connection complete.
[2025-07-26T08:26:55.070+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Closing connection. 
[2025-07-26T08:26:55.484+0000] {cluster.py:313} WARNING - Topic orders_topic is not available during auto-create initialization
[2025-07-26T08:26:55.594+0000] {cluster.py:313} WARNING - Topic orders_topic is not available during auto-create initialization
[2025-07-26T08:26:55.703+0000] {cluster.py:313} WARNING - Topic orders_topic is not available during auto-create initialization
[2025-07-26T08:26:55.811+0000] {cluster.py:313} WARNING - Topic orders_topic is not available during auto-create initialization
[2025-07-26T08:26:56.008+0000] {logging_mixin.py:188} INFO - ‚úÖ Produced 124 records to topic 'orders_topic'
[2025-07-26T08:26:56.009+0000] {logging_mixin.py:188} INFO - ‚úÖ Orders producer completed
[2025-07-26T08:26:56.011+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.7', 9092)]>: connecting to kafka:9092 [('172.18.0.7', 9092) IPv4]
[2025-07-26T08:26:56.018+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.7', 9092)]>: Broker version identified as 2.6
[2025-07-26T08:26:56.019+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Connection complete.
[2025-07-26T08:26:56.024+0000] {subscription_state.py:181} INFO - Updating subscribed topics to: ('orders_topic',)
[2025-07-26T08:26:56.090+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.7', 9092)]>: connecting to kafka:9092 [('172.18.0.7', 9092) IPv4]
[2025-07-26T08:26:56.092+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Connection complete.
[2025-07-26T08:26:56.093+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Closing connection. 
[2025-07-26T08:26:59.776+0000] {cluster.py:401} INFO - Coordinator for group/etl_group is ('coordinator-1', 'kafka', 9092, None)
[2025-07-26T08:26:59.777+0000] {base.py:788} INFO - Discovered coordinator coordinator-1 for group etl_group
[2025-07-26T08:26:59.778+0000] {base.py:848} INFO - Starting new heartbeat thread
[2025-07-26T08:26:59.779+0000] {consumer.py:365} INFO - Revoking previously assigned partitions () for group etl_group
[2025-07-26T08:26:59.780+0000] {base.py:419} INFO - Failed to join group etl_group: NodeNotReadyError: coordinator-1
[2025-07-26T08:26:59.781+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.7', 9092)]>: connecting to kafka:9092 [('172.18.0.7', 9092) IPv4]
[2025-07-26T08:26:59.782+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Connection complete.
[2025-07-26T08:26:59.883+0000] {base.py:532} INFO - (Re-)joining group etl_group
[2025-07-26T08:26:59.920+0000] {base.py:637} INFO - Received member id kafka-python-2.2.15-313a2d6c-19be-4c6e-860b-9486f6dffada for group etl_group; will retry join-group
[2025-07-26T08:26:59.920+0000] {base.py:419} INFO - Failed to join group etl_group: [Error 79] MemberIdRequiredError
[2025-07-26T08:26:59.921+0000] {base.py:532} INFO - (Re-)joining group etl_group
[2025-07-26T08:27:02.959+0000] {base.py:594} INFO - Successfully joined group etl_group <Generation 1 (member_id: kafka-python-2.2.15-313a2d6c-19be-4c6e-860b-9486f6dffada, protocol: range)>
[2025-07-26T08:27:02.961+0000] {base.py:596} INFO - Elected group leader -- performing partition assignments using range
[2025-07-26T08:27:02.995+0000] {subscription_state.py:254} INFO - Updated partition assignment: [('orders_topic', 0)]
[2025-07-26T08:27:02.996+0000] {consumer.py:249} INFO - Setting newly assigned partitions (('orders_topic', 0),) for group etl_group
[2025-07-26T08:27:03.035+0000] {fetcher.py:418} INFO - Resetting offset for partition ('orders_topic', 0) to offset 0.
[2025-07-26T08:27:03.730+0000] {logging_mixin.py:188} INFO - üìù Inserted 100 into orders...
[2025-07-26T08:38:16.473+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-07-26T08:38:16.482+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-07-26T08:38:16.486+0000] {process_utils.py:132} INFO - Sending 15 to group 51. PIDs of all processes in the group: [51]
[2025-07-26T08:38:16.488+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 51
[2025-07-26T08:38:16.493+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-07-26T08:38:16.508+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-26T08:38:16.710+0000] {base.py:1052} INFO - Stopping heartbeat thread
[2025-07-26T08:38:16.782+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=51, status='terminated', exitcode=0, started='08:26:52') (51) terminated with exit code 0
