[2025-07-26T06:09:51.301+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-26T06:09:51.370+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sample_ETL.load_order_and_delivery_data manual__2025-07-26T06:09:42.039350+00:00 [queued]>
[2025-07-26T06:09:51.382+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sample_ETL.load_order_and_delivery_data manual__2025-07-26T06:09:42.039350+00:00 [queued]>
[2025-07-26T06:09:51.383+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-26T06:09:51.424+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_order_and_delivery_data> on 2025-07-26 06:09:42.039350+00:00
[2025-07-26T06:09:51.443+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=70) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-26T06:09:51.445+0000] {standard_task_runner.py:63} INFO - Started process 71 to run task
[2025-07-26T06:09:51.444+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sample_ETL', 'load_order_and_delivery_data', 'manual__2025-07-26T06:09:42.039350+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/sample_ETL.py', '--cfg-path', '/tmp/tmpi9hnd9r8']
[2025-07-26T06:09:51.446+0000] {standard_task_runner.py:91} INFO - Job 59: Subtask load_order_and_delivery_data
[2025-07-26T06:09:51.596+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-26T06:09:51.718+0000] {task_command.py:426} INFO - Running <TaskInstance: sample_ETL.load_order_and_delivery_data manual__2025-07-26T06:09:42.039350+00:00 [running]> on host 0d20e4fb6b68
[2025-07-26T06:09:52.090+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sample_ETL' AIRFLOW_CTX_TASK_ID='load_order_and_delivery_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-26T06:09:42.039350+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-26T06:09:42.039350+00:00'
[2025-07-26T06:09:52.093+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-26T06:09:52.114+0000] {logging_mixin.py:188} INFO - üöÄ Starting load_order_and_delivery_data
[2025-07-26T06:09:52.125+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.9', 9092)]>: connecting to kafka:9092 [('172.18.0.9', 9092) IPv4]
[2025-07-26T06:09:52.321+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.9', 9092)]>: Broker version identified as 2.6
[2025-07-26T06:09:52.322+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.9', 9092)]>: Connection complete.
[2025-07-26T06:09:52.513+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.9', 9092)]>: connecting to kafka:9092 [('172.18.0.9', 9092) IPv4]
[2025-07-26T06:09:52.514+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.9', 9092)]>: Connection complete.
[2025-07-26T06:09:52.515+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.9', 9092)]>: Closing connection. 
[2025-07-26T06:09:52.738+0000] {cluster.py:313} WARNING - Topic orders_topic is not available during auto-create initialization
[2025-07-26T06:09:52.852+0000] {cluster.py:313} WARNING - Topic orders_topic is not available during auto-create initialization
[2025-07-26T06:09:52.963+0000] {cluster.py:313} WARNING - Topic orders_topic is not available during auto-create initialization
[2025-07-26T06:09:53.073+0000] {cluster.py:313} WARNING - Topic orders_topic is not available during auto-create initialization
[2025-07-26T06:09:53.186+0000] {cluster.py:313} WARNING - Topic orders_topic is not available during auto-create initialization
[2025-07-26T06:09:53.524+0000] {logging_mixin.py:188} INFO - ‚úÖ Produced 124 records to topic 'orders_topic'
[2025-07-26T06:09:53.525+0000] {logging_mixin.py:188} INFO - ‚úÖ orders producer completed
[2025-07-26T06:09:53.590+0000] {cluster.py:313} WARNING - Topic delivery_topic is not available during auto-create initialization
[2025-07-26T06:09:53.717+0000] {logging_mixin.py:188} INFO - ‚úÖ Produced 124 records to topic 'delivery_topic'
[2025-07-26T06:09:53.718+0000] {logging_mixin.py:188} INFO - ‚úÖ delivery producer completed
[2025-07-26T06:09:58.723+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.9', 9092)]>: connecting to kafka:9092 [('172.18.0.9', 9092) IPv4]
[2025-07-26T06:09:58.730+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.9', 9092)]>: Broker version identified as 2.6
[2025-07-26T06:09:58.730+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.9', 9092)]>: Connection complete.
[2025-07-26T06:09:58.732+0000] {subscription_state.py:181} INFO - Updating subscribed topics to: ('orders_topic',)
[2025-07-26T06:09:58.796+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.9', 9092)]>: connecting to kafka:9092 [('172.18.0.9', 9092) IPv4]
[2025-07-26T06:09:58.797+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.9', 9092)]>: Connection complete.
[2025-07-26T06:09:58.798+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.9', 9092)]>: Closing connection. 
[2025-07-26T06:10:01.550+0000] {cluster.py:401} INFO - Coordinator for group/etl_group is ('coordinator-1', 'kafka', 9092, None)
[2025-07-26T06:10:01.551+0000] {base.py:788} INFO - Discovered coordinator coordinator-1 for group etl_group
[2025-07-26T06:10:01.552+0000] {base.py:848} INFO - Starting new heartbeat thread
[2025-07-26T06:10:01.553+0000] {consumer.py:365} INFO - Revoking previously assigned partitions () for group etl_group
[2025-07-26T06:10:01.554+0000] {base.py:419} INFO - Failed to join group etl_group: NodeNotReadyError: coordinator-1
[2025-07-26T06:10:01.555+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.9', 9092)]>: connecting to kafka:9092 [('172.18.0.9', 9092) IPv4]
[2025-07-26T06:10:01.556+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connected> [IPv4 ('172.18.0.9', 9092)]>: Connection complete.
[2025-07-26T06:10:01.658+0000] {base.py:532} INFO - (Re-)joining group etl_group
[2025-07-26T06:10:01.680+0000] {base.py:637} INFO - Received member id kafka-python-2.2.15-eba99808-993d-43fb-af19-a5251f621b82 for group etl_group; will retry join-group
[2025-07-26T06:10:01.681+0000] {base.py:419} INFO - Failed to join group etl_group: [Error 79] MemberIdRequiredError
[2025-07-26T06:10:01.682+0000] {base.py:532} INFO - (Re-)joining group etl_group
[2025-07-26T06:10:04.716+0000] {base.py:594} INFO - Successfully joined group etl_group <Generation 1 (member_id: kafka-python-2.2.15-eba99808-993d-43fb-af19-a5251f621b82, protocol: range)>
[2025-07-26T06:10:04.718+0000] {base.py:596} INFO - Elected group leader -- performing partition assignments using range
[2025-07-26T06:10:04.749+0000] {subscription_state.py:254} INFO - Updated partition assignment: [('orders_topic', 0)]
[2025-07-26T06:10:04.750+0000] {consumer.py:249} INFO - Setting newly assigned partitions (('orders_topic', 0),) for group etl_group
[2025-07-26T06:10:04.777+0000] {fetcher.py:418} INFO - Resetting offset for partition ('orders_topic', 0) to offset 0.
[2025-07-26T06:10:04.906+0000] {logging_mixin.py:188} INFO - üìù Inserted 100 into orders...
[2025-07-26T07:17:43.439+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-07-26T07:17:43.571+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-07-26T07:17:43.738+0000] {process_utils.py:132} INFO - Sending 15 to group 71. PIDs of all processes in the group: [71]
[2025-07-26T07:17:43.748+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 71
[2025-07-26T07:17:43.792+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-07-26T07:17:43.989+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-26T07:17:45.937+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=71, status='terminated', exitcode=0, started='06:09:50') (71) terminated with exit code 0
