[2025-07-26T08:02:56.946+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-26T08:02:57.015+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sample_ETL.load_order_and_delivery_data manual__2025-07-26T08:02:49.579980+00:00 [queued]>
[2025-07-26T08:02:57.026+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sample_ETL.load_order_and_delivery_data manual__2025-07-26T08:02:49.579980+00:00 [queued]>
[2025-07-26T08:02:57.027+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-26T08:02:57.059+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_order_and_delivery_data> on 2025-07-26 08:02:49.579980+00:00
[2025-07-26T08:02:57.069+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=120) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-26T08:02:57.070+0000] {standard_task_runner.py:63} INFO - Started process 121 to run task
[2025-07-26T08:02:57.069+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sample_ETL', 'load_order_and_delivery_data', 'manual__2025-07-26T08:02:49.579980+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/sample_ETL.py', '--cfg-path', '/tmp/tmphrbn79bn']
[2025-07-26T08:02:57.071+0000] {standard_task_runner.py:91} INFO - Job 66: Subtask load_order_and_delivery_data
[2025-07-26T08:02:57.155+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-26T08:02:57.271+0000] {task_command.py:426} INFO - Running <TaskInstance: sample_ETL.load_order_and_delivery_data manual__2025-07-26T08:02:49.579980+00:00 [running]> on host 11bcfbb7cdb0
[2025-07-26T08:02:57.532+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sample_ETL' AIRFLOW_CTX_TASK_ID='load_order_and_delivery_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-26T08:02:49.579980+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-26T08:02:49.579980+00:00'
[2025-07-26T08:02:57.534+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-26T08:02:57.549+0000] {logging_mixin.py:188} INFO - üöÄ Starting ETL with JSON files
[2025-07-26T08:02:57.557+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.9', 9092)]>: connecting to kafka:9092 [('172.18.0.9', 9092) IPv4]
[2025-07-26T08:02:57.729+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.9', 9092)]>: Broker version identified as 2.6
[2025-07-26T08:02:57.729+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.9', 9092)]>: Connection complete.
[2025-07-26T08:02:57.840+0000] {logging_mixin.py:188} INFO - ‚ùå Invalid JSON in orders.json
[2025-07-26T08:02:57.842+0000] {logging_mixin.py:188} INFO - ‚úÖ Orders producer completed
[2025-07-26T08:02:57.844+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.9', 9092)]>: connecting to kafka:9092 [('172.18.0.9', 9092) IPv4]
[2025-07-26T08:02:57.853+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.9', 9092)]>: Broker version identified as 2.6
[2025-07-26T08:02:57.854+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.9', 9092)]>: Connection complete.
[2025-07-26T08:02:57.857+0000] {subscription_state.py:181} INFO - Updating subscribed topics to: ('orders_topic',)
[2025-07-26T08:02:58.110+0000] {cluster.py:313} WARNING - Topic orders_topic is not available during auto-create initialization
[2025-07-26T08:02:58.112+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.9', 9092)]>: connecting to kafka:9092 [('172.18.0.9', 9092) IPv4]
[2025-07-26T08:02:58.113+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.9', 9092)]>: Connection complete.
[2025-07-26T08:02:58.113+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.9', 9092)]>: Closing connection. 
[2025-07-26T08:03:00.922+0000] {cluster.py:401} INFO - Coordinator for group/etl_group is ('coordinator-1', 'kafka', 9092, None)
[2025-07-26T08:03:00.923+0000] {base.py:788} INFO - Discovered coordinator coordinator-1 for group etl_group
[2025-07-26T08:03:00.924+0000] {base.py:848} INFO - Starting new heartbeat thread
[2025-07-26T08:03:00.925+0000] {consumer.py:365} INFO - Revoking previously assigned partitions () for group etl_group
[2025-07-26T08:03:00.926+0000] {base.py:419} INFO - Failed to join group etl_group: NodeNotReadyError: coordinator-1
[2025-07-26T08:03:00.927+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.9', 9092)]>: connecting to kafka:9092 [('172.18.0.9', 9092) IPv4]
[2025-07-26T08:03:00.929+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connected> [IPv4 ('172.18.0.9', 9092)]>: Connection complete.
[2025-07-26T08:03:01.030+0000] {base.py:532} INFO - (Re-)joining group etl_group
[2025-07-26T08:03:01.060+0000] {base.py:637} INFO - Received member id kafka-python-2.2.15-3bb0c474-4eb3-4d91-af31-8682529ed794 for group etl_group; will retry join-group
[2025-07-26T08:03:01.061+0000] {base.py:419} INFO - Failed to join group etl_group: [Error 79] MemberIdRequiredError
[2025-07-26T08:03:01.061+0000] {base.py:532} INFO - (Re-)joining group etl_group
[2025-07-26T08:03:04.099+0000] {base.py:594} INFO - Successfully joined group etl_group <Generation 1 (member_id: kafka-python-2.2.15-3bb0c474-4eb3-4d91-af31-8682529ed794, protocol: range)>
[2025-07-26T08:03:04.101+0000] {base.py:596} INFO - Elected group leader -- performing partition assignments using range
[2025-07-26T08:03:04.102+0000] {range.py:47} WARNING - No partition metadata for topic orders_topic
[2025-07-26T08:03:04.198+0000] {subscription_state.py:254} INFO - Updated partition assignment: []
[2025-07-26T08:03:04.199+0000] {consumer.py:249} INFO - Setting newly assigned partitions () for group etl_group
[2025-07-26T08:03:07.203+0000] {consumer.py:365} INFO - Revoking previously assigned partitions () for group etl_group
[2025-07-26T08:03:07.207+0000] {base.py:532} INFO - (Re-)joining group etl_group
[2025-07-26T08:03:07.214+0000] {base.py:594} INFO - Successfully joined group etl_group <Generation 2 (member_id: kafka-python-2.2.15-3bb0c474-4eb3-4d91-af31-8682529ed794, protocol: range)>
[2025-07-26T08:03:07.215+0000] {base.py:596} INFO - Elected group leader -- performing partition assignments using range
[2025-07-26T08:03:07.222+0000] {subscription_state.py:254} INFO - Updated partition assignment: [('orders_topic', 0)]
[2025-07-26T08:03:07.223+0000] {consumer.py:249} INFO - Setting newly assigned partitions (('orders_topic', 0),) for group etl_group
[2025-07-26T08:03:07.255+0000] {fetcher.py:418} INFO - Resetting offset for partition ('orders_topic', 0) to offset 0.
[2025-07-26T08:06:38.210+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-07-26T08:06:38.217+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-07-26T08:06:38.229+0000] {process_utils.py:132} INFO - Sending 15 to group 121. PIDs of all processes in the group: [121]
[2025-07-26T08:06:38.230+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 121
[2025-07-26T08:06:38.233+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-07-26T08:06:38.242+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-26T08:06:38.643+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=121, status='terminated', exitcode=0, started='08:02:56') (121) terminated with exit code 0
